class Loading extends HTMLElement {
  constructor() {
    super();

    this._shadowRoot = this.attachShadow({ mode: "open" });
  }

  _emptyContent() {
    this._shadowRoot.innerHTML = "";
  }


  connectedCallback() {
    this.render();
  }

  render() {
    this._emptyContent();

    this._shadowRoot.innerHTML = `
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="100"
          height="200" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);"
          xmlns:xlink="http://www.w3.org/1999/xlink">
          <g>
              <circle stroke-dasharray="164.93361431346415 56.97787143782138" r="35" stroke-width="10"
                  stroke="#405cf5" fill="none" cy="50" cx="50">
                  <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="1s" repeatCount="indefinite"
                      type="rotate" attributeName="transform"></animateTransform>
              </circle>
              <g></g>
          </g><!-- [ldio] generated by https://loading.io -->
      </svg>
    `;
  }
}

customElements.define("loading-element", Loading);